### ISSUE TITLE
Cannot find module 'augment-vir/dist/node'

### ISSUE THREAD

**Issue by keganlance** [electrovir/stylelint-plugin-import#19]
When running the plugin, I'm getting the following error:
```
Cannot find module 'augment-vir/dist/node' from 'node_modules/.pnpm/stylelint-rule-creator@5.0.0/node_modules/stylelint-rule-creator/dist/default-rule.js'
```

This might have to do with the fact this plugin is using an outdated version of [stylelint-rule-creator](https://github.com/electrovir/stylelint-rule-creator).

**Comment by electrovir** [comment]
I haven't been able to reproduce this locally yet, but I went ahead and updated this package's dependencies anyway and published that under version `1.0.11`. Can you please try that version and see if it works?

**Comment by keganlance** [comment]
@electrovir Seems `1.0.11` still uses stylelint-rule-creator `5.0.0`.

**Comment by electrovir** [comment]
Weird, [ncu](https://www.npmjs.com/package/npm-check-updates) didn't catch that update 🤔 I'll have to update the dep version manually I guess 😆

**Comment by electrovir** [comment]
I updated this package again to [v1.0.12](https://www.npmjs.com/package/stylelint-plugin-import/v/1.0.12). Please try this version out!

**Comment by keganlance** [comment]
That did the trick, thank you so much!
